import type { ITheme } from '@xterm/xterm'

export type AppThemeMode = 'light' | 'dark'
export type AppThemePreset = 'mulberry' | 'studio' | 'graphite' | 'ocean' | 'forest' | 'dawn'
export type SshTerminalThemePreset = AppThemePreset

type ThemeCssVars = Record<`--${string}`, string>

type ThemePreviewPalette = {
  rail: string
  canvas: string
  card: string
  accent: string
  accentSoft: string
  text: string
}

export type SshChromePalette = {
  libraryFrameStart: string
  libraryFrameEnd: string
  libraryBorder: string
  libraryText: string
  connectFrame: string
  connectBorder: string
  connectText: string
  terminalFrame: string
  terminalBorder: string
  terminalText: string
  canvas: string
  canvasSubtle: string
  terminalCanvas: string
  panel: string
  panelStrong: string
  panelBorder: string
  surface: string
  surfaceStrong: string
  text: string
  muted: string
  accent: string
  accentSoft: string
  accentContrast: string
  success: string
  successSoft: string
  warning: string
  warningSoft: string
  danger: string
  dangerSoft: string
  badge: string
  libraryPill: string
  libraryPillActive: string
  libraryPillText: string
  libraryPillActiveText: string
  connectPill: string
  connectPillActive: string
  connectPillText: string
  connectPillActiveText: string
  terminalPill: string
  terminalPillActive: string
  terminalPillText: string
  terminalPillActiveText: string
}

export type ThemePresetDefinition = {
  id: AppThemePreset
  labelKey: string
  descriptionKey: string
  swatches: [string, string, string]
  preview: Record<AppThemeMode, ThemePreviewPalette>
  cssVars: Record<AppThemeMode, ThemeCssVars>
  terminal: Record<AppThemeMode, ITheme>
  ssh: Record<AppThemeMode, SshChromePalette>
}

export const DEFAULT_APP_THEME_PRESET: AppThemePreset = 'mulberry'
export const DEFAULT_SSH_TERMINAL_THEME_PRESET: SshTerminalThemePreset = DEFAULT_APP_THEME_PRESET

function createTerminalTheme(colors: {
  background: string
  foreground: string
  selectionBackground: string
  cursor?: string
  black: string
  red: string
  green: string
  yellow: string
  blue: string
  magenta: string
  cyan: string
  white: string
  brightBlack: string
  brightRed: string
  brightGreen: string
  brightYellow: string
  brightBlue: string
  brightMagenta: string
  brightCyan: string
  brightWhite: string
}): ITheme {
  return {
    background: colors.background,
    foreground: colors.foreground,
    cursor: colors.cursor ?? colors.foreground,
    cursorAccent: colors.background,
    selectionBackground: colors.selectionBackground,
    black: colors.black,
    red: colors.red,
    green: colors.green,
    yellow: colors.yellow,
    blue: colors.blue,
    magenta: colors.magenta,
    cyan: colors.cyan,
    white: colors.white,
    brightBlack: colors.brightBlack,
    brightRed: colors.brightRed,
    brightGreen: colors.brightGreen,
    brightYellow: colors.brightYellow,
    brightBlue: colors.brightBlue,
    brightMagenta: colors.brightMagenta,
    brightCyan: colors.brightCyan,
    brightWhite: colors.brightWhite
  }
}

const PRESET_DEFINITIONS: Record<AppThemePreset, ThemePresetDefinition> = {
  mulberry: {
    id: 'mulberry',
    labelKey: 'general.themePreset.presets.mulberry.label',
    descriptionKey: 'general.themePreset.presets.mulberry.desc',
    swatches: ['#171a18', '#7f9a8e', '#d89f4a'],
    preview: {
      light: {
        rail: '#eef1ed',
        canvas: '#f8f7f2',
        card: '#ffffff',
        accent: '#31594e',
        accentSoft: '#dde8e1',
        text: '#171a18'
      },
      dark: {
        rail: '#111613',
        canvas: '#151817',
        card: '#202522',
        accent: '#9bbcac',
        accentSoft: '#27332d',
        text: '#f2f0e8'
      }
    },
    cssVars: {
      light: {
        '--background': '#f8f7f2',
        '--foreground': '#171a18',
        '--card': '#fffdfa',
        '--card-foreground': '#171a18',
        '--popover': '#fffdfa',
        '--popover-foreground': '#171a18',
        '--primary': '#31594e',
        '--primary-foreground': '#f8f7f2',
        '--secondary': '#eef1ed',
        '--secondary-foreground': '#24302b',
        '--muted': '#f0eee7',
        '--muted-foreground': '#69736c',
        '--accent': '#dde8e1',
        '--accent-foreground': '#20322c',
        '--destructive': '#dc2626',
        '--destructive-foreground': '#fafafa',
        '--border': '#d9d5c9',
        '--input': '#d9d5c9',
        '--ring': '#7f9a8e',
        '--chart-1': '#31594e',
        '--chart-2': '#d89f4a',
        '--chart-3': '#69736c',
        '--chart-4': '#8b6f4e',
        '--chart-5': '#b8c6be',
        '--sidebar': '#eef1ed',
        '--sidebar-foreground': '#171a18',
        '--sidebar-primary': '#31594e',
        '--sidebar-primary-foreground': '#f8f7f2',
        '--sidebar-accent': '#dde8e1',
        '--sidebar-accent-foreground': '#20322c',
        '--sidebar-border': '#d6ddd6',
        '--sidebar-ring': '#7f9a8e',
        '--workspace-titlebar-bg': '#f8f7f2',
        '--workspace-titlebar-border': '#e4dfd3',
        '--workspace-titlebar-button-hover': '#ebe8df',
        '--workspace-titlebar-toolgroup-bg': '#fffdfa',
        '--workspace-titlebar-toolgroup-border': '#d9d5c9',
        '--workspace-titlebar-toolbutton-hover': '#eef1ed',
        '--workspace-titlebar-toolbutton-active': '#dde8e1',
        '--workspace-sidebar-divider': '#d6ddd6',
        '--workspace-sidebar-section-border': '#e0e3dc',
        '--workspace-sidebar-row-hover-bg': '#e2eae4',
        '--workspace-sidebar-row-hover-border': '#cad7cf',
        '--workspace-sidebar-row-active-bg': '#d5e3dc',
        '--workspace-sidebar-row-active-border': '#bccfc5',
        '--workspace-sidebar-row-active-shadow': '0 12px 22px -18px rgba(49, 89, 78, 0.2)',
        '--activity-card-bg': '#fffdfa',
        '--activity-card-border': '#d9d5c9',
        '--activity-card-divider': '#ebe8df',
        '--activity-card-header-hover': '#eef1ed',
        '--activity-card-shadow': '0 18px 34px -26px rgba(23, 26, 24, 0.16)',
        '--composer-shell-top': '#fffdfa',
        '--composer-shell-bottom': '#fbfaf5',
        '--composer-shell-border': '#d9d5c9',
        '--composer-shell-border-focus': 'color-mix(in srgb, #7f9a8e 34%, #d9d5c9)',
        '--composer-shell-shadow':
          '0 18px 34px -26px rgba(23, 26, 24, 0.16), 0 1px 2px rgba(23, 26, 24, 0.06)',
        '--composer-shell-shadow-focus':
          '0 20px 38px -26px rgba(23, 26, 24, 0.18), 0 0 0 3px rgba(127, 154, 142, 0.14)',
        '--composer-toolbar-border': '#ebe8df',
        '--composer-panel-bg': '#fffdfa',
        '--composer-panel-border': '#d9d5c9',
        '--composer-panel-shadow':
          '0 22px 40px -30px rgba(23, 26, 24, 0.16), 0 1px 2px rgba(23, 26, 24, 0.06)',
        '--composer-control-bg-hover': '#eef1ed',
        '--composer-control-active-text': '#171a18',
        '--composer-send-start': '#31594e',
        '--composer-send-end': '#223d36',
        '--composer-send-foreground': '#f8f7f2',
        '--composer-chip-border': '#d9d5c9',
        '--composer-chip-text': '#56645d',
        '--composer-chip-hover': '#eef1ed',
        '--composer-drop-bg': '#dde8e1'
      },
      dark: {
        '--background': '#151817',
        '--foreground': '#f2f0e8',
        '--card': '#202522',
        '--card-foreground': '#f2f0e8',
        '--popover': '#242a27',
        '--popover-foreground': '#f2f0e8',
        '--primary': '#9bbcac',
        '--primary-foreground': '#101411',
        '--secondary': '#242a27',
        '--secondary-foreground': '#f2f0e8',
        '--muted': '#1b201d',
        '--muted-foreground': '#a9b3ab',
        '--accent': '#27332d',
        '--accent-foreground': '#f2f0e8',
        '--destructive': '#7f1d1d',
        '--destructive-foreground': '#fafafa',
        '--border': '#374039',
        '--input': '#374039',
        '--ring': '#7f9a8e',
        '--chart-1': '#9bbcac',
        '--chart-2': '#d89f4a',
        '--chart-3': '#a9b3ab',
        '--chart-4': '#7b9aa6',
        '--chart-5': '#5f746a',
        '--sidebar': '#111613',
        '--sidebar-foreground': '#f2f0e8',
        '--sidebar-primary': '#9bbcac',
        '--sidebar-primary-foreground': '#101411',
        '--sidebar-accent': '#1d2722',
        '--sidebar-accent-foreground': '#f2f0e8',
        '--sidebar-border': '#27332d',
        '--sidebar-ring': '#7f9a8e',
        '--workspace-titlebar-bg': '#151817',
        '--workspace-titlebar-border': '#27332d',
        '--workspace-titlebar-button-hover': '#27332d',
        '--workspace-titlebar-toolgroup-bg': '#202522',
        '--workspace-titlebar-toolgroup-border': '#374039',
        '--workspace-titlebar-toolbutton-hover': '#27332d',
        '--workspace-titlebar-toolbutton-active': '#34443c',
        '--workspace-sidebar-divider': '#27332d',
        '--workspace-sidebar-section-border': '#27332d',
        '--workspace-sidebar-row-hover-bg': '#1d2722',
        '--workspace-sidebar-row-hover-border': '#34443c',
        '--workspace-sidebar-row-active-bg': '#27332d',
        '--workspace-sidebar-row-active-border': '#466055',
        '--workspace-sidebar-row-active-shadow': '0 16px 28px -24px rgba(0, 0, 0, 0.58)',
        '--activity-card-bg': '#202522',
        '--activity-card-border': '#374039',
        '--activity-card-divider': '#27332d',
        '--activity-card-header-hover': '#27332d',
        '--activity-card-shadow': '0 20px 36px -26px rgba(0, 0, 0, 0.48)',
        '--composer-shell-top': '#242a27',
        '--composer-shell-bottom': '#202522',
        '--composer-shell-border': '#374039',
        '--composer-shell-border-focus': 'color-mix(in srgb, #7f9a8e 32%, #374039)',
        '--composer-shell-shadow':
          '0 20px 34px -24px rgba(0, 0, 0, 0.44), 0 1px 2px rgba(0, 0, 0, 0.26)',
        '--composer-shell-shadow-focus':
          '0 24px 40px -24px rgba(0, 0, 0, 0.5), 0 0 0 3px rgba(127, 154, 142, 0.14)',
        '--composer-toolbar-border': '#374039',
        '--composer-panel-bg': '#242a27',
        '--composer-panel-border': '#374039',
        '--composer-panel-shadow':
          '0 22px 40px -28px rgba(0, 0, 0, 0.48), 0 1px 2px rgba(0, 0, 0, 0.26)',
        '--composer-control-bg-hover': '#27332d',
        '--composer-control-active-text': '#f2f0e8',
        '--composer-send-start': '#9bbcac',
        '--composer-send-end': '#d89f4a',
        '--composer-send-foreground': '#101411',
        '--composer-chip-border': '#374039',
        '--composer-chip-text': '#c8d0c9',
        '--composer-chip-hover': '#27332d',
        '--composer-drop-bg': '#27332d'
      }
    },
    terminal: {
      light: createTerminalTheme({
        background: '#ffffff',
        foreground: '#09090b',
        selectionBackground: 'rgba(24, 24, 27, 0.12)',
        cursor: '#18181b',
        black: '#09090b',
        red: '#ef4444',
        green: '#22c55e',
        yellow: '#eab308',
        blue: '#3b82f6',
        magenta: '#a855f7',
        cyan: '#06b6d4',
        white: '#e4e4e7',
        brightBlack: '#71717a',
        brightRed: '#f87171',
        brightGreen: '#4ade80',
        brightYellow: '#facc15',
        brightBlue: '#60a5fa',
        brightMagenta: '#c084fc',
        brightCyan: '#22d3ee',
        brightWhite: '#ffffff'
      }),
      dark: createTerminalTheme({
        background: '#09090b',
        foreground: '#fafafa',
        selectionBackground: 'rgba(250, 250, 250, 0.16)',
        cursor: '#fafafa',
        black: '#09090b',
        red: '#f87171',
        green: '#4ade80',
        yellow: '#facc15',
        blue: '#60a5fa',
        magenta: '#c084fc',
        cyan: '#22d3ee',
        white: '#fafafa',
        brightBlack: '#71717a',
        brightRed: '#fca5a5',
        brightGreen: '#86efac',
        brightYellow: '#fde047',
        brightBlue: '#93c5fd',
        brightMagenta: '#d8b4fe',
        brightCyan: '#67e8f9',
        brightWhite: '#ffffff'
      })
    },
    ssh: {
      light: {
        libraryFrameStart: '#18181b',
        libraryFrameEnd: '#2a2a2e',
        libraryBorder: 'rgba(255,255,255,0.08)',
        libraryText: '#fafafa',
        connectFrame: '#fafafa',
        connectBorder: '#e4e4e7',
        connectText: '#52525b',
        terminalFrame: '#18181b',
        terminalBorder: 'rgba(255,255,255,0.08)',
        terminalText: '#fafafa',
        canvas: '#fafafa',
        canvasSubtle: '#ffffff',
        terminalCanvas: '#09090b',
        panel: '#18181b',
        panelStrong: '#09090b',
        panelBorder: 'rgba(255,255,255,0.08)',
        surface: '#ffffff',
        surfaceStrong: '#fafafa',
        text: '#09090b',
        muted: '#71717a',
        accent: '#18181b',
        accentSoft: '#f4f4f5',
        accentContrast: '#fafafa',
        success: '#16a34a',
        successSoft: '#f0fdf4',
        warning: '#ca8a04',
        warningSoft: '#fefce8',
        danger: '#dc2626',
        dangerSoft: '#fef2f2',
        badge: '#18181b',
        libraryPill: 'rgba(255,255,255,0.1)',
        libraryPillActive: 'rgba(255,255,255,0.16)',
        libraryPillText: '#f4f4f5',
        libraryPillActiveText: '#ffffff',
        connectPill: '#f4f4f5',
        connectPillActive: '#e4e4e7',
        connectPillText: '#52525b',
        connectPillActiveText: '#18181b',
        terminalPill: 'rgba(255,255,255,0.08)',
        terminalPillActive: '#27272a',
        terminalPillText: '#e4e4e7',
        terminalPillActiveText: '#fafafa'
      },
      dark: {
        libraryFrameStart: '#09090b',
        libraryFrameEnd: '#18181b',
        libraryBorder: 'rgba(255,255,255,0.08)',
        libraryText: '#fafafa',
        connectFrame: '#09090b',
        connectBorder: '#27272a',
        connectText: '#a1a1aa',
        terminalFrame: '#09090b',
        terminalBorder: 'rgba(255,255,255,0.08)',
        terminalText: '#fafafa',
        canvas: '#09090b',
        canvasSubtle: '#111113',
        terminalCanvas: '#09090b',
        panel: '#18181b',
        panelStrong: '#111113',
        panelBorder: 'rgba(255,255,255,0.08)',
        surface: '#18181b',
        surfaceStrong: '#202024',
        text: '#fafafa',
        muted: '#a1a1aa',
        accent: '#fafafa',
        accentSoft: '#27272a',
        accentContrast: '#18181b',
        success: '#4ade80',
        successSoft: '#052e16',
        warning: '#facc15',
        warningSoft: '#422006',
        danger: '#f87171',
        dangerSoft: '#450a0a',
        badge: '#fafafa',
        libraryPill: 'rgba(255,255,255,0.08)',
        libraryPillActive: 'rgba(255,255,255,0.14)',
        libraryPillText: '#e4e4e7',
        libraryPillActiveText: '#ffffff',
        connectPill: '#18181b',
        connectPillActive: '#27272a',
        connectPillText: '#a1a1aa',
        connectPillActiveText: '#fafafa',
        terminalPill: 'rgba(255,255,255,0.08)',
        terminalPillActive: '#27272a',
        terminalPillText: '#e4e4e7',
        terminalPillActiveText: '#fafafa'
      }
    }
  },
  studio: {
    id: 'studio',
    labelKey: 'general.themePreset.presets.studio.label',
    descriptionKey: 'general.themePreset.presets.studio.desc',
    swatches: ['#3558e8', '#7aa7ff', '#f08f61'],
    preview: {
      light: {
        rail: '#304064',
        canvas: '#eef2f6',
        card: '#ffffff',
        accent: '#3558e8',
        accentSoft: '#dfe8ff',
        text: '#202b41'
      },
      dark: {
        rail: '#162032',
        canvas: '#101726',
        card: '#1d2740',
        accent: '#79a6ff',
        accentSoft: '#293650',
        text: '#f4f7ff'
      }
    },
    cssVars: {
      light: {
        '--background': '#f4f7fb',
        '--foreground': '#172033',
        '--card': '#ffffff',
        '--card-foreground': '#172033',
        '--popover': '#ffffff',
        '--popover-foreground': '#172033',
        '--primary': '#3558e8',
        '--primary-foreground': '#f8fbff',
        '--secondary': '#e9eef7',
        '--secondary-foreground': '#2a3750',
        '--muted': '#eef2f8',
        '--muted-foreground': '#6b7892',
        '--accent': '#e4ebff',
        '--accent-foreground': '#22315a',
        '--destructive': '#d65353',
        '--destructive-foreground': '#ffffff',
        '--border': '#d6dfec',
        '--input': '#d6dfec',
        '--ring': '#6f84ff',
        '--chart-1': '#3558e8',
        '--chart-2': '#00a3bf',
        '--chart-3': '#f08f61',
        '--chart-4': '#56ae74',
        '--chart-5': '#d7a53f',
        '--sidebar': '#f8fbff',
        '--sidebar-foreground': '#172033',
        '--sidebar-primary': '#3558e8',
        '--sidebar-primary-foreground': '#f8fbff',
        '--sidebar-accent': '#ebf1ff',
        '--sidebar-accent-foreground': '#20305b',
        '--sidebar-border': '#d6dfec',
        '--sidebar-ring': '#6f84ff'
      },
      dark: {
        '--background': '#101726',
        '--foreground': '#f4f7ff',
        '--card': '#1d2740',
        '--card-foreground': '#f4f7ff',
        '--popover': '#233049',
        '--popover-foreground': '#f4f7ff',
        '--primary': '#79a6ff',
        '--primary-foreground': '#0b1220',
        '--secondary': '#202c44',
        '--secondary-foreground': '#edf2ff',
        '--muted': '#192338',
        '--muted-foreground': '#92a0bd',
        '--accent': '#293650',
        '--accent-foreground': '#f5f7ff',
        '--destructive': '#ff7f8c',
        '--destructive-foreground': '#2a1116',
        '--border': '#364663',
        '--input': '#364663',
        '--ring': '#7aa7ff',
        '--chart-1': '#79a6ff',
        '--chart-2': '#67d6f3',
        '--chart-3': '#f2a272',
        '--chart-4': '#69cf8e',
        '--chart-5': '#ebc15e',
        '--sidebar': '#162032',
        '--sidebar-foreground': '#f4f7ff',
        '--sidebar-primary': '#79a6ff',
        '--sidebar-primary-foreground': '#0b1220',
        '--sidebar-accent': '#233049',
        '--sidebar-accent-foreground': '#f4f7ff',
        '--sidebar-border': '#33435f',
        '--sidebar-ring': '#7aa7ff'
      }
    },
    terminal: {
      light: createTerminalTheme({
        background: '#f7faff',
        foreground: '#1d2740',
        selectionBackground: 'rgba(53, 88, 232, 0.18)',
        cursor: '#3558e8',
        black: '#1f2740',
        red: '#cc4e62',
        green: '#1f8c57',
        yellow: '#c98517',
        blue: '#3558e8',
        magenta: '#8d63d2',
        cyan: '#0287a0',
        white: '#dfe7f7',
        brightBlack: '#7f8aa5',
        brightRed: '#e26d81',
        brightGreen: '#31a36c',
        brightYellow: '#dda13a',
        brightBlue: '#5877f0',
        brightMagenta: '#a989df',
        brightCyan: '#26a8c0',
        brightWhite: '#ffffff'
      }),
      dark: createTerminalTheme({
        background: '#151b30',
        foreground: '#d7e1ff',
        selectionBackground: 'rgba(121, 157, 255, 0.22)',
        cursor: '#dbfff0',
        black: '#151b30',
        red: '#ff7a93',
        green: '#35e0a1',
        yellow: '#f0c56e',
        blue: '#75a7ff',
        magenta: '#d4a8ff',
        cyan: '#7be4f6',
        white: '#d7e1ff',
        brightBlack: '#7282a1',
        brightRed: '#ff9bb0',
        brightGreen: '#5ff1ba',
        brightYellow: '#ffd98d',
        brightBlue: '#93bcff',
        brightMagenta: '#e1c0ff',
        brightCyan: '#9df0ff',
        brightWhite: '#f4f7ff'
      })
    },
    ssh: {
      light: {
        libraryFrameStart: '#304064',
        libraryFrameEnd: '#4a4568',
        libraryBorder: 'rgba(255,255,255,0.08)',
        libraryText: '#eef4ff',
        connectFrame: '#f0f3f6',
        connectBorder: '#d8dee6',
        connectText: '#5b6678',
        terminalFrame: '#191f35',
        terminalBorder: 'rgba(255,255,255,0.08)',
        terminalText: '#dbe6ff',
        canvas: '#eef2f6',
        canvasSubtle: '#f6f8fb',
        terminalCanvas: '#14192d',
        panel: '#161d33',
        panelStrong: '#11172a',
        panelBorder: 'rgba(255,255,255,0.08)',
        surface: '#ffffff',
        surfaceStrong: '#f5f8fb',
        text: '#22304a',
        muted: '#8291a6',
        accent: '#2f8cf3',
        accentSoft: '#deebff',
        accentContrast: '#ffffff',
        success: '#1f8c57',
        successSoft: '#ebf8ef',
        warning: '#c78413',
        warningSoft: '#fff4dc',
        danger: '#d25555',
        dangerSoft: '#fff0f0',
        badge: '#2f8cf3',
        libraryPill: 'rgba(255,255,255,0.1)',
        libraryPillActive: 'rgba(255,255,255,0.16)',
        libraryPillText: '#d3dbef',
        libraryPillActiveText: '#ffffff',
        connectPill: '#dfe5ea',
        connectPillActive: '#cfd5dd',
        connectPillText: '#6a7688',
        connectPillActiveText: '#2f3851',
        terminalPill: 'rgba(255,255,255,0.06)',
        terminalPillActive: '#173d34',
        terminalPillText: '#b7c4e5',
        terminalPillActiveText: '#4ef0a8'
      },
      dark: {
        libraryFrameStart: '#18213a',
        libraryFrameEnd: '#252340',
        libraryBorder: 'rgba(255,255,255,0.1)',
        libraryText: '#eef4ff',
        connectFrame: '#121927',
        connectBorder: '#243046',
        connectText: '#9daccc',
        terminalFrame: '#111828',
        terminalBorder: 'rgba(255,255,255,0.08)',
        terminalText: '#e7eeff',
        canvas: '#0f1524',
        canvasSubtle: '#12192a',
        terminalCanvas: '#0b1220',
        panel: '#11182a',
        panelStrong: '#0c1322',
        panelBorder: 'rgba(255,255,255,0.08)',
        surface: '#171f31',
        surfaceStrong: '#1c2538',
        text: '#edf3ff',
        muted: '#97a5c4',
        accent: '#79a6ff',
        accentSoft: '#203763',
        accentContrast: '#0b1220',
        success: '#5de0ad',
        successSoft: '#14251f',
        warning: '#f0c56e',
        warningSoft: '#2a2314',
        danger: '#ff90a4',
        dangerSoft: '#281620',
        badge: '#79a6ff',
        libraryPill: 'rgba(255,255,255,0.08)',
        libraryPillActive: 'rgba(255,255,255,0.14)',
        libraryPillText: '#cdd7ef',
        libraryPillActiveText: '#ffffff',
        connectPill: '#182233',
        connectPillActive: '#23324a',
        connectPillText: '#9daccc',
        connectPillActiveText: '#f4f7ff',
        terminalPill: 'rgba(255,255,255,0.06)',
        terminalPillActive: '#1b3c39',
        terminalPillText: '#c6d2eb',
        terminalPillActiveText: '#7cf0b6'
      }
    }
  },
  graphite: {
    id: 'graphite',
    labelKey: 'general.themePreset.presets.graphite.label',
    descriptionKey: 'general.themePreset.presets.graphite.desc',
    swatches: ['#2a7b73', '#7fd4c9', '#7b8798'],
    preview: {
      light: {
        rail: '#3f4349',
        canvas: '#f3f4f5',
        card: '#ffffff',
        accent: '#2a7b73',
        accentSoft: '#dcecea',
        text: '#17191d'
      },
      dark: {
        rail: '#1d232a',
        canvas: '#171b20',
        card: '#272e36',
        accent: '#7cd8cb',
        accentSoft: '#313840',
        text: '#f5f8f7'
      }
    },
    cssVars: {
      light: {
        '--background': '#f3f4f5',
        '--foreground': '#17191d',
        '--card': '#ffffff',
        '--card-foreground': '#17191d',
        '--popover': '#ffffff',
        '--popover-foreground': '#17191d',
        '--primary': '#2a7b73',
        '--primary-foreground': '#f7fbfa',
        '--secondary': '#e8ecec',
        '--secondary-foreground': '#243133',
        '--muted': '#edf0f0',
        '--muted-foreground': '#667276',
        '--accent': '#e2ebea',
        '--accent-foreground': '#1c3131',
        '--destructive': '#c85656',
        '--destructive-foreground': '#ffffff',
        '--border': '#d5dbdc',
        '--input': '#d5dbdc',
        '--ring': '#68bfb2',
        '--chart-1': '#2a7b73',
        '--chart-2': '#4aa09a',
        '--chart-3': '#8894a4',
        '--chart-4': '#d2a66d',
        '--chart-5': '#8b6262',
        '--sidebar': '#f7f8f8',
        '--sidebar-foreground': '#17191d',
        '--sidebar-primary': '#2a7b73',
        '--sidebar-primary-foreground': '#f7fbfa',
        '--sidebar-accent': '#edf2f2',
        '--sidebar-accent-foreground': '#213536',
        '--sidebar-border': '#d5dbdc',
        '--sidebar-ring': '#68bfb2'
      },
      dark: {
        '--background': '#171b20',
        '--foreground': '#f5f8f7',
        '--card': '#272e36',
        '--card-foreground': '#f5f8f7',
        '--popover': '#2d353d',
        '--popover-foreground': '#f5f8f7',
        '--primary': '#7cd8cb',
        '--primary-foreground': '#0d1617',
        '--secondary': '#2a3139',
        '--secondary-foreground': '#eef3f2',
        '--muted': '#21272d',
        '--muted-foreground': '#a7b2b0',
        '--accent': '#313840',
        '--accent-foreground': '#f1f5f4',
        '--destructive': '#ff9898',
        '--destructive-foreground': '#2b1515',
        '--border': '#434c52',
        '--input': '#434c52',
        '--ring': '#86ddd1',
        '--chart-1': '#7cd8cb',
        '--chart-2': '#8eb7ff',
        '--chart-3': '#9ba6b7',
        '--chart-4': '#d8b57a',
        '--chart-5': '#ff9f8d',
        '--sidebar': '#1d232a',
        '--sidebar-foreground': '#f5f8f7',
        '--sidebar-primary': '#7cd8cb',
        '--sidebar-primary-foreground': '#0d1617',
        '--sidebar-accent': '#2b323a',
        '--sidebar-accent-foreground': '#f5f8f7',
        '--sidebar-border': '#414a50',
        '--sidebar-ring': '#86ddd1',
        '--workspace-titlebar-bg': '#1d232a',
        '--workspace-titlebar-border': '#343c40',
        '--workspace-titlebar-button-hover': '#2a3035',
        '--workspace-titlebar-toolgroup-bg': '#20262b',
        '--workspace-titlebar-toolgroup-border': '#394246',
        '--workspace-titlebar-toolbutton-hover': '#30373c',
        '--workspace-titlebar-toolbutton-active': '#394145',
        '--workspace-sidebar-divider': '#343c40',
        '--workspace-sidebar-section-border': '#31383d',
        '--workspace-sidebar-row-hover-bg': '#2b3136',
        '--workspace-sidebar-row-hover-border': '#3b4449',
        '--workspace-sidebar-row-active-bg': '#343c41',
        '--workspace-sidebar-row-active-border': '#4a565c',
        '--workspace-sidebar-row-active-shadow': '0 14px 24px -22px rgba(0, 0, 0, 0.38)',
        '--activity-card-bg': '#282f37',
        '--activity-card-border': '#394246',
        '--activity-card-divider': '#333c40',
        '--activity-card-header-hover': '#2d3439',
        '--activity-card-shadow': '0 18px 32px -24px rgba(0, 0, 0, 0.42)',
        '--composer-shell-top': '#2a3138',
        '--composer-shell-bottom': '#232931',
        '--composer-shell-border': '#3b4448',
        '--composer-shell-border-focus': 'color-mix(in srgb, #86ddd1 26%, #3b4448)',
        '--composer-shell-shadow':
          '0 18px 32px -24px rgba(0, 0, 0, 0.44), 0 1px 2px rgba(0, 0, 0, 0.26)',
        '--composer-shell-shadow-focus':
          '0 22px 36px -24px rgba(0, 0, 0, 0.5), 0 0 0 3px rgba(134, 221, 209, 0.12)',
        '--composer-toolbar-border': '#394246',
        '--composer-panel-bg': '#303840',
        '--composer-panel-border': '#3b4448',
        '--composer-panel-shadow':
          '0 22px 40px -28px rgba(0, 0, 0, 0.52), 0 1px 2px rgba(0, 0, 0, 0.28)',
        '--composer-control-bg-hover': '#313840',
        '--composer-control-active-text': '#f5f8f7',
        '--composer-send-start': '#f1f5f4',
        '--composer-send-end': '#f1f5f4',
        '--composer-send-foreground': '#182023',
        '--composer-chip-border': '#394246',
        '--composer-chip-text': '#c1cbca',
        '--composer-chip-hover': '#2b3136',
        '--composer-drop-bg': '#374145'
      }
    },
    terminal: {
      light: createTerminalTheme({
        background: '#f5f7f7',
        foreground: '#1b2124',
        selectionBackground: 'rgba(42, 123, 115, 0.18)',
        cursor: '#2a7b73',
        black: '#1b2124',
        red: '#c85656',
        green: '#1f8b76',
        yellow: '#b98a3d',
        blue: '#5678ad',
        magenta: '#7f6b9d',
        cyan: '#328d86',
        white: '#dfe6e6',
        brightBlack: '#768186',
        brightRed: '#d96b6b',
        brightGreen: '#36a691',
        brightYellow: '#caa253',
        brightBlue: '#6f90c6',
        brightMagenta: '#9580b3',
        brightCyan: '#4da9a2',
        brightWhite: '#ffffff'
      }),
      dark: createTerminalTheme({
        background: '#171c20',
        foreground: '#e8efee',
        selectionBackground: 'rgba(124, 216, 203, 0.22)',
        cursor: '#e8efee',
        black: '#171c20',
        red: '#ff9494',
        green: '#7cd8cb',
        yellow: '#e4c077',
        blue: '#93b1ff',
        magenta: '#beabd8',
        cyan: '#85e4d8',
        white: '#e8efee',
        brightBlack: '#879396',
        brightRed: '#ffb0b0',
        brightGreen: '#97e8de',
        brightYellow: '#f2d596',
        brightBlue: '#adc5ff',
        brightMagenta: '#cebce4',
        brightCyan: '#a7efe7',
        brightWhite: '#f8fcfb'
      })
    },
    ssh: {
      light: {
        libraryFrameStart: '#3f4349',
        libraryFrameEnd: '#59616a',
        libraryBorder: 'rgba(255,255,255,0.08)',
        libraryText: '#f7fbfa',
        connectFrame: '#eff2f2',
        connectBorder: '#d7dddd',
        connectText: '#5e6668',
        terminalFrame: '#1a2023',
        terminalBorder: 'rgba(255,255,255,0.08)',
        terminalText: '#dbe4e3',
        canvas: '#eff2f2',
        canvasSubtle: '#f6f8f8',
        terminalCanvas: '#12171a',
        panel: '#161d20',
        panelStrong: '#11171a',
        panelBorder: 'rgba(255,255,255,0.08)',
        surface: '#ffffff',
        surfaceStrong: '#f5f7f7',
        text: '#1f2529',
        muted: '#7b878d',
        accent: '#2a7b73',
        accentSoft: '#dcecea',
        accentContrast: '#ffffff',
        success: '#287a64',
        successSoft: '#e8f7f0',
        warning: '#b98a3d',
        warningSoft: '#fff5df',
        danger: '#c85656',
        dangerSoft: '#fff1f1',
        badge: '#2a7b73',
        libraryPill: 'rgba(255,255,255,0.1)',
        libraryPillActive: 'rgba(255,255,255,0.16)',
        libraryPillText: '#dbe4e3',
        libraryPillActiveText: '#ffffff',
        connectPill: '#e2e7e7',
        connectPillActive: '#d4dbdb',
        connectPillText: '#657072',
        connectPillActiveText: '#263133',
        terminalPill: 'rgba(255,255,255,0.06)',
        terminalPillActive: '#1f3936',
        terminalPillText: '#cbd7d6',
        terminalPillActiveText: '#8ce8db'
      },
      dark: {
        libraryFrameStart: '#20262b',
        libraryFrameEnd: '#2b3339',
        libraryBorder: 'rgba(255,255,255,0.1)',
        libraryText: '#f5f8f7',
        connectFrame: '#171b1f',
        connectBorder: '#354045',
        connectText: '#aab5b7',
        terminalFrame: '#161b1f',
        terminalBorder: 'rgba(255,255,255,0.1)',
        terminalText: '#eef5f4',
        canvas: '#171b20',
        canvasSubtle: '#1b2025',
        terminalCanvas: '#151a1d',
        panel: '#20262b',
        panelStrong: '#191f23',
        panelBorder: 'rgba(255,255,255,0.1)',
        surface: '#272d32',
        surfaceStrong: '#2f363c',
        text: '#eef5f4',
        muted: '#a5b0b2',
        accent: '#7cd8cb',
        accentSoft: '#223c39',
        accentContrast: '#0d1617',
        success: '#88e5ce',
        successSoft: '#152824',
        warning: '#e4c077',
        warningSoft: '#2d2618',
        danger: '#ffabab',
        dangerSoft: '#311b1b',
        badge: '#7cd8cb',
        libraryPill: 'rgba(255,255,255,0.1)',
        libraryPillActive: 'rgba(255,255,255,0.16)',
        libraryPillText: '#dbe5e4',
        libraryPillActiveText: '#ffffff',
        connectPill: '#21282c',
        connectPillActive: '#2d383d',
        connectPillText: '#b0bbbd',
        connectPillActiveText: '#f5f8f7',
        terminalPill: 'rgba(255,255,255,0.08)',
        terminalPillActive: '#294743',
        terminalPillText: '#d7e3e2',
        terminalPillActiveText: '#a9f3e8'
      }
    }
  },
  ocean: {
    id: 'ocean',
    labelKey: 'general.themePreset.presets.ocean.label',
    descriptionKey: 'general.themePreset.presets.ocean.desc',
    swatches: ['#0f8aa6', '#4cc9f0', '#8be3ff'],
    preview: {
      light: {
        rail: '#0f5162',
        canvas: '#eef7f8',
        card: '#ffffff',
        accent: '#0f8aa6',
        accentSoft: '#d7f0f6',
        text: '#13232a'
      },
      dark: {
        rail: '#0d202c',
        canvas: '#081823',
        card: '#122733',
        accent: '#4cc9f0',
        accentSoft: '#183342',
        text: '#eefbff'
      }
    },
    cssVars: {
      light: {
        '--background': '#eef7f8',
        '--foreground': '#13232a',
        '--card': '#ffffff',
        '--card-foreground': '#13232a',
        '--popover': '#ffffff',
        '--popover-foreground': '#13232a',
        '--primary': '#0f8aa6',
        '--primary-foreground': '#f4fdff',
        '--secondary': '#dff0f4',
        '--secondary-foreground': '#1b3540',
        '--muted': '#e7f3f6',
        '--muted-foreground': '#5c7580',
        '--accent': '#d7f0f6',
        '--accent-foreground': '#123844',
        '--destructive': '#d65f58',
        '--destructive-foreground': '#ffffff',
        '--border': '#c9e1e7',
        '--input': '#c9e1e7',
        '--ring': '#4cbad8',
        '--chart-1': '#0f8aa6',
        '--chart-2': '#4cc9f0',
        '--chart-3': '#1380b9',
        '--chart-4': '#65b58d',
        '--chart-5': '#db9f51',
        '--sidebar': '#f5fbfc',
        '--sidebar-foreground': '#13232a',
        '--sidebar-primary': '#0f8aa6',
        '--sidebar-primary-foreground': '#f4fdff',
        '--sidebar-accent': '#e2f5f8',
        '--sidebar-accent-foreground': '#123844',
        '--sidebar-border': '#c9e1e7',
        '--sidebar-ring': '#4cbad8'
      },
      dark: {
        '--background': '#081823',
        '--foreground': '#eefbff',
        '--card': '#122733',
        '--card-foreground': '#eefbff',
        '--popover': '#15303d',
        '--popover-foreground': '#eefbff',
        '--primary': '#4cc9f0',
        '--primary-foreground': '#07202a',
        '--secondary': '#13303d',
        '--secondary-foreground': '#eefbff',
        '--muted': '#0f2430',
        '--muted-foreground': '#8fb0bd',
        '--accent': '#183342',
        '--accent-foreground': '#eefbff',
        '--destructive': '#ff8d82',
        '--destructive-foreground': '#2d130f',
        '--border': '#284958',
        '--input': '#284958',
        '--ring': '#72d9ff',
        '--chart-1': '#4cc9f0',
        '--chart-2': '#8be3ff',
        '--chart-3': '#7aa8ff',
        '--chart-4': '#67d39a',
        '--chart-5': '#ffc87a',
        '--sidebar': '#0d202c',
        '--sidebar-foreground': '#eefbff',
        '--sidebar-primary': '#4cc9f0',
        '--sidebar-primary-foreground': '#07202a',
        '--sidebar-accent': '#14303d',
        '--sidebar-accent-foreground': '#eefbff',
        '--sidebar-border': '#254553',
        '--sidebar-ring': '#72d9ff'
      }
    },
    terminal: {
      light: createTerminalTheme({
        background: '#f4fdff',
        foreground: '#17303a',
        selectionBackground: 'rgba(15, 138, 166, 0.18)',
        cursor: '#0f8aa6',
        black: '#17303a',
        red: '#d66166',
        green: '#1fa87d',
        yellow: '#c99841',
        blue: '#147db2',
        magenta: '#5d7fd6',
        cyan: '#0f8aa6',
        white: '#dbeff4',
        brightBlack: '#6c8a95',
        brightRed: '#ea7a7a',
        brightGreen: '#36c49a',
        brightYellow: '#deae5d',
        brightBlue: '#329ad0',
        brightMagenta: '#7798eb',
        brightCyan: '#34afd2',
        brightWhite: '#ffffff'
      }),
      dark: createTerminalTheme({
        background: '#0b1a23',
        foreground: '#def7ff',
        selectionBackground: 'rgba(76, 201, 240, 0.18)',
        cursor: '#bdf3ff',
        black: '#0b1a23',
        red: '#ff8f90',
        green: '#57e1af',
        yellow: '#ffd279',
        blue: '#71c9ff',
        magenta: '#93b3ff',
        cyan: '#66e3ff',
        white: '#def7ff',
        brightBlack: '#6f92a2',
        brightRed: '#ffb1b2',
        brightGreen: '#80f0c7',
        brightYellow: '#ffe39d',
        brightBlue: '#93d7ff',
        brightMagenta: '#b1c6ff',
        brightCyan: '#8feeff',
        brightWhite: '#f3fdff'
      })
    },
    ssh: {
      light: {
        libraryFrameStart: '#0f5162',
        libraryFrameEnd: '#17667a',
        libraryBorder: 'rgba(255,255,255,0.08)',
        libraryText: '#eefcff',
        connectFrame: '#eef7f8',
        connectBorder: '#d2e3e7',
        connectText: '#5d747d',
        terminalFrame: '#0d2230',
        terminalBorder: 'rgba(255,255,255,0.08)',
        terminalText: '#ddf6ff',
        canvas: '#eef7f8',
        canvasSubtle: '#f6fbfc',
        terminalCanvas: '#0b1a23',
        panel: '#102431',
        panelStrong: '#0b1a23',
        panelBorder: 'rgba(255,255,255,0.08)',
        surface: '#ffffff',
        surfaceStrong: '#f4fbfc',
        text: '#18303a',
        muted: '#7c939c',
        accent: '#0f8aa6',
        accentSoft: '#d7f0f6',
        accentContrast: '#ffffff',
        success: '#1c996f',
        successSoft: '#e7f8f0',
        warning: '#cc9540',
        warningSoft: '#fff5e1',
        danger: '#d66166',
        dangerSoft: '#fff1f1',
        badge: '#0f8aa6',
        libraryPill: 'rgba(255,255,255,0.1)',
        libraryPillActive: 'rgba(255,255,255,0.16)',
        libraryPillText: '#d8eef3',
        libraryPillActiveText: '#ffffff',
        connectPill: '#dfecef',
        connectPillActive: '#cfdee2',
        connectPillText: '#60767d',
        connectPillActiveText: '#17313b',
        terminalPill: 'rgba(255,255,255,0.06)',
        terminalPillActive: '#15424b',
        terminalPillText: '#c7e2eb',
        terminalPillActiveText: '#84f0ff'
      },
      dark: {
        libraryFrameStart: '#08202d',
        libraryFrameEnd: '#0c3042',
        libraryBorder: 'rgba(255,255,255,0.08)',
        libraryText: '#eefbff',
        connectFrame: '#081823',
        connectBorder: '#183443',
        connectText: '#98b7c3',
        terminalFrame: '#08151d',
        terminalBorder: 'rgba(255,255,255,0.08)',
        terminalText: '#eefbff',
        canvas: '#081823',
        canvasSubtle: '#0b1b25',
        terminalCanvas: '#07141c',
        panel: '#0d202b',
        panelStrong: '#081823',
        panelBorder: 'rgba(255,255,255,0.08)',
        surface: '#102632',
        surfaceStrong: '#14303d',
        text: '#eefbff',
        muted: '#93b1bd',
        accent: '#4cc9f0',
        accentSoft: '#153b48',
        accentContrast: '#07202a',
        success: '#6ae1b6',
        successSoft: '#11241d',
        warning: '#ffd279',
        warningSoft: '#2a2213',
        danger: '#ff9fa2',
        dangerSoft: '#281618',
        badge: '#4cc9f0',
        libraryPill: 'rgba(255,255,255,0.08)',
        libraryPillActive: 'rgba(255,255,255,0.14)',
        libraryPillText: '#d4eff6',
        libraryPillActiveText: '#ffffff',
        connectPill: '#102531',
        connectPillActive: '#173646',
        connectPillText: '#9cb7c1',
        connectPillActiveText: '#eefbff',
        terminalPill: 'rgba(255,255,255,0.06)',
        terminalPillActive: '#15444d',
        terminalPillText: '#d3edf5',
        terminalPillActiveText: '#90f3ff'
      }
    }
  },
  forest: {
    id: 'forest',
    labelKey: 'general.themePreset.presets.forest.label',
    descriptionKey: 'general.themePreset.presets.forest.desc',
    swatches: ['#2f8b57', '#6fd39a', '#98e0a0'],
    preview: {
      light: {
        rail: '#244937',
        canvas: '#f4f8f4',
        card: '#ffffff',
        accent: '#2f8b57',
        accentSoft: '#e1f1e6',
        text: '#16221b'
      },
      dark: {
        rail: '#122119',
        canvas: '#0d1913',
        card: '#17261d',
        accent: '#6fd39a',
        accentSoft: '#1d3025',
        text: '#effbf3'
      }
    },
    cssVars: {
      light: {
        '--background': '#f4f8f4',
        '--foreground': '#16221b',
        '--card': '#ffffff',
        '--card-foreground': '#16221b',
        '--popover': '#ffffff',
        '--popover-foreground': '#16221b',
        '--primary': '#2f8b57',
        '--primary-foreground': '#f6fff8',
        '--secondary': '#e5efe7',
        '--secondary-foreground': '#22372a',
        '--muted': '#ebf3ec',
        '--muted-foreground': '#67796d',
        '--accent': '#e1f1e6',
        '--accent-foreground': '#1d3a28',
        '--destructive': '#c95e5e',
        '--destructive-foreground': '#ffffff',
        '--border': '#d6e3d8',
        '--input': '#d6e3d8',
        '--ring': '#59b87d',
        '--chart-1': '#2f8b57',
        '--chart-2': '#64b287',
        '--chart-3': '#96c36b',
        '--chart-4': '#dfb35c',
        '--chart-5': '#c77e5c',
        '--sidebar': '#f8fbf8',
        '--sidebar-foreground': '#16221b',
        '--sidebar-primary': '#2f8b57',
        '--sidebar-primary-foreground': '#f6fff8',
        '--sidebar-accent': '#edf5ef',
        '--sidebar-accent-foreground': '#1d3a28',
        '--sidebar-border': '#d6e3d8',
        '--sidebar-ring': '#59b87d'
      },
      dark: {
        '--background': '#0d1913',
        '--foreground': '#effbf3',
        '--card': '#17261d',
        '--card-foreground': '#effbf3',
        '--popover': '#1c2d22',
        '--popover-foreground': '#effbf3',
        '--primary': '#6fd39a',
        '--primary-foreground': '#0b1d13',
        '--secondary': '#1a2b20',
        '--secondary-foreground': '#effbf3',
        '--muted': '#122118',
        '--muted-foreground': '#93ae9b',
        '--accent': '#1d3025',
        '--accent-foreground': '#effbf3',
        '--destructive': '#ff9494',
        '--destructive-foreground': '#2b1515',
        '--border': '#31523f',
        '--input': '#31523f',
        '--ring': '#88e2af',
        '--chart-1': '#6fd39a',
        '--chart-2': '#98e0a0',
        '--chart-3': '#b9d665',
        '--chart-4': '#f0c275',
        '--chart-5': '#ff9d78',
        '--sidebar': '#122119',
        '--sidebar-foreground': '#effbf3',
        '--sidebar-primary': '#6fd39a',
        '--sidebar-primary-foreground': '#0b1d13',
        '--sidebar-accent': '#1a2c21',
        '--sidebar-accent-foreground': '#effbf3',
        '--sidebar-border': '#2e4d3b',
        '--sidebar-ring': '#88e2af'
      }
    },
    terminal: {
      light: createTerminalTheme({
        background: '#f7fcf8',
        foreground: '#1c2a22',
        selectionBackground: 'rgba(47, 139, 87, 0.16)',
        cursor: '#2f8b57',
        black: '#1c2a22',
        red: '#c86464',
        green: '#2f8b57',
        yellow: '#bf963d',
        blue: '#508f70',
        magenta: '#758b65',
        cyan: '#1b9b84',
        white: '#dfefe4',
        brightBlack: '#74837a',
        brightRed: '#dc7c7c',
        brightGreen: '#48a56f',
        brightYellow: '#d3ab56',
        brightBlue: '#6ca98a',
        brightMagenta: '#8aa17a',
        brightCyan: '#39b29c',
        brightWhite: '#ffffff'
      }),
      dark: createTerminalTheme({
        background: '#0d1712',
        foreground: '#e1f5e6',
        selectionBackground: 'rgba(111, 211, 154, 0.18)',
        cursor: '#c3f6d6',
        black: '#0d1712',
        red: '#ff9d9d',
        green: '#6fd39a',
        yellow: '#ebc777',
        blue: '#8bd3ae',
        magenta: '#b8cc7a',
        cyan: '#73e3c9',
        white: '#e1f5e6',
        brightBlack: '#6d8976',
        brightRed: '#ffbdbd',
        brightGreen: '#92e3b4',
        brightYellow: '#f4d996',
        brightBlue: '#addfc0',
        brightMagenta: '#cddd9a',
        brightCyan: '#97efdb',
        brightWhite: '#f5fdf7'
      })
    },
    ssh: {
      light: {
        libraryFrameStart: '#244937',
        libraryFrameEnd: '#355744',
        libraryBorder: 'rgba(255,255,255,0.08)',
        libraryText: '#f5fff7',
        connectFrame: '#f2f7f2',
        connectBorder: '#d7e3d9',
        connectText: '#607368',
        terminalFrame: '#13231b',
        terminalBorder: 'rgba(255,255,255,0.08)',
        terminalText: '#e4f7eb',
        canvas: '#f2f7f2',
        canvasSubtle: '#f8fbf8',
        terminalCanvas: '#0d1712',
        panel: '#12231b',
        panelStrong: '#0d1712',
        panelBorder: 'rgba(255,255,255,0.08)',
        surface: '#ffffff',
        surfaceStrong: '#f5faf6',
        text: '#1d2a22',
        muted: '#7b8d82',
        accent: '#2f8b57',
        accentSoft: '#e1f1e6',
        accentContrast: '#ffffff',
        success: '#2f8b57',
        successSoft: '#e8f8ed',
        warning: '#bf963d',
        warningSoft: '#fff5e0',
        danger: '#c86464',
        dangerSoft: '#fff1f1',
        badge: '#2f8b57',
        libraryPill: 'rgba(255,255,255,0.1)',
        libraryPillActive: 'rgba(255,255,255,0.16)',
        libraryPillText: '#dcecdf',
        libraryPillActiveText: '#ffffff',
        connectPill: '#e3ebe5',
        connectPillActive: '#d5dfd7',
        connectPillText: '#63766a',
        connectPillActiveText: '#20332a',
        terminalPill: 'rgba(255,255,255,0.06)',
        terminalPillActive: '#1e402c',
        terminalPillText: '#d4e7da',
        terminalPillActiveText: '#9ef0bd'
      },
      dark: {
        libraryFrameStart: '#12231b',
        libraryFrameEnd: '#173227',
        libraryBorder: 'rgba(255,255,255,0.08)',
        libraryText: '#effcf3',
        connectFrame: '#0d1913',
        connectBorder: '#20392d',
        connectText: '#98af9e',
        terminalFrame: '#0d1712',
        terminalBorder: 'rgba(255,255,255,0.08)',
        terminalText: '#effcf3',
        canvas: '#0d1913',
        canvasSubtle: '#101c15',
        terminalCanvas: '#0b1410',
        panel: '#11201a',
        panelStrong: '#0d1913',
        panelBorder: 'rgba(255,255,255,0.08)',
        surface: '#15241c',
        surfaceStrong: '#193027',
        text: '#effcf3',
        muted: '#93aa99',
        accent: '#6fd39a',
        accentSoft: '#173b28',
        accentContrast: '#0b1d13',
        success: '#86e3ad',
        successSoft: '#11231b',
        warning: '#ebc777',
        warningSoft: '#2a2415',
        danger: '#ffaaaa',
        dangerSoft: '#291717',
        badge: '#6fd39a',
        libraryPill: 'rgba(255,255,255,0.08)',
        libraryPillActive: 'rgba(255,255,255,0.14)',
        libraryPillText: '#d7e8dc',
        libraryPillActiveText: '#ffffff',
        connectPill: '#16271e',
        connectPillActive: '#20372a',
        connectPillText: '#9eb5a4',
        connectPillActiveText: '#effcf3',
        terminalPill: 'rgba(255,255,255,0.06)',
        terminalPillActive: '#1f412e',
        terminalPillText: '#daeade',
        terminalPillActiveText: '#a9f3c5'
      }
    }
  },
  dawn: {
    id: 'dawn',
    labelKey: 'general.themePreset.presets.dawn.label',
    descriptionKey: 'general.themePreset.presets.dawn.desc',
    swatches: ['#ca6a33', '#ffb27d', '#ffd8a8'],
    preview: {
      light: {
        rail: '#6a402f',
        canvas: '#fbf6f2',
        card: '#ffffff',
        accent: '#ca6a33',
        accentSoft: '#f9e5da',
        text: '#2b1d19'
      },
      dark: {
        rail: '#2a1911',
        canvas: '#22140e',
        card: '#312016',
        accent: '#ffb27d',
        accentSoft: '#3f291c',
        text: '#fff4eb'
      }
    },
    cssVars: {
      light: {
        '--background': '#fbf6f2',
        '--foreground': '#2b1d19',
        '--card': '#ffffff',
        '--card-foreground': '#2b1d19',
        '--popover': '#ffffff',
        '--popover-foreground': '#2b1d19',
        '--primary': '#ca6a33',
        '--primary-foreground': '#fffaf7',
        '--secondary': '#f3e8df',
        '--secondary-foreground': '#473025',
        '--muted': '#f7eee7',
        '--muted-foreground': '#7f665c',
        '--accent': '#f9e5da',
        '--accent-foreground': '#5f3824',
        '--destructive': '#cc6258',
        '--destructive-foreground': '#ffffff',
        '--border': '#ead6cb',
        '--input': '#ead6cb',
        '--ring': '#e99568',
        '--chart-1': '#ca6a33',
        '--chart-2': '#ff9a63',
        '--chart-3': '#d79c52',
        '--chart-4': '#b49068',
        '--chart-5': '#8f6464',
        '--sidebar': '#fdf9f6',
        '--sidebar-foreground': '#2b1d19',
        '--sidebar-primary': '#ca6a33',
        '--sidebar-primary-foreground': '#fffaf7',
        '--sidebar-accent': '#fbede4',
        '--sidebar-accent-foreground': '#5f3824',
        '--sidebar-border': '#ead6cb',
        '--sidebar-ring': '#e99568'
      },
      dark: {
        '--background': '#22140e',
        '--foreground': '#fff4eb',
        '--card': '#312016',
        '--card-foreground': '#fff4eb',
        '--popover': '#382519',
        '--popover-foreground': '#fff4eb',
        '--primary': '#ffb27d',
        '--primary-foreground': '#341a0e',
        '--secondary': '#372418',
        '--secondary-foreground': '#fff4eb',
        '--muted': '#2c1c13',
        '--muted-foreground': '#c7ac9b',
        '--accent': '#3f291c',
        '--accent-foreground': '#fff4eb',
        '--destructive': '#ff9d8b',
        '--destructive-foreground': '#331611',
        '--border': '#5d3d29',
        '--input': '#5d3d29',
        '--ring': '#ffbf90',
        '--chart-1': '#ffb27d',
        '--chart-2': '#ffd8a8',
        '--chart-3': '#f3c66b',
        '--chart-4': '#d6a07e',
        '--chart-5': '#ff9b8b',
        '--sidebar': '#2a1911',
        '--sidebar-foreground': '#fff4eb',
        '--sidebar-primary': '#ffb27d',
        '--sidebar-primary-foreground': '#341a0e',
        '--sidebar-accent': '#392519',
        '--sidebar-accent-foreground': '#fff4eb',
        '--sidebar-border': '#593924',
        '--sidebar-ring': '#ffbf90'
      }
    },
    terminal: {
      light: createTerminalTheme({
        background: '#fffaf6',
        foreground: '#33221c',
        selectionBackground: 'rgba(202, 106, 51, 0.16)',
        cursor: '#ca6a33',
        black: '#33221c',
        red: '#cc6258',
        green: '#7e9b57',
        yellow: '#cb9547',
        blue: '#d17d49',
        magenta: '#9d745b',
        cyan: '#b8804b',
        white: '#f2e3da',
        brightBlack: '#8c7165',
        brightRed: '#df7b70',
        brightGreen: '#96b26c',
        brightYellow: '#ddac60',
        brightBlue: '#e6915e',
        brightMagenta: '#b28b73',
        brightCyan: '#cf9965',
        brightWhite: '#ffffff'
      }),
      dark: createTerminalTheme({
        background: '#26160f',
        foreground: '#ffe9d8',
        selectionBackground: 'rgba(255, 178, 125, 0.18)',
        cursor: '#ffd8a8',
        black: '#26160f',
        red: '#ff9d8b',
        green: '#9fd17c',
        yellow: '#ffd17c',
        blue: '#ffb27d',
        magenta: '#d6a07e',
        cyan: '#ffc18e',
        white: '#ffe9d8',
        brightBlack: '#9c7761',
        brightRed: '#ffb8ab',
        brightGreen: '#b8e499',
        brightYellow: '#ffe09c',
        brightBlue: '#ffc69c',
        brightMagenta: '#e3b493',
        brightCyan: '#ffd3ae',
        brightWhite: '#fff8f2'
      })
    },
    ssh: {
      light: {
        libraryFrameStart: '#6a402f',
        libraryFrameEnd: '#87563e',
        libraryBorder: 'rgba(255,255,255,0.08)',
        libraryText: '#fff6ef',
        connectFrame: '#f8f2ed',
        connectBorder: '#ebdbd1',
        connectText: '#7b675e',
        terminalFrame: '#2a1a12',
        terminalBorder: 'rgba(255,255,255,0.08)',
        terminalText: '#ffe8d9',
        canvas: '#f8f2ed',
        canvasSubtle: '#fdf9f5',
        terminalCanvas: '#26160f',
        panel: '#2d1d14',
        panelStrong: '#26160f',
        panelBorder: 'rgba(255,255,255,0.08)',
        surface: '#ffffff',
        surfaceStrong: '#fdf7f3',
        text: '#33231c',
        muted: '#8d7568',
        accent: '#ca6a33',
        accentSoft: '#f9e5da',
        accentContrast: '#ffffff',
        success: '#7e9b57',
        successSoft: '#eef5e5',
        warning: '#cb9547',
        warningSoft: '#fff3df',
        danger: '#cc6258',
        dangerSoft: '#fff1f0',
        badge: '#ca6a33',
        libraryPill: 'rgba(255,255,255,0.1)',
        libraryPillActive: 'rgba(255,255,255,0.16)',
        libraryPillText: '#f0ddd2',
        libraryPillActiveText: '#ffffff',
        connectPill: '#efe4dc',
        connectPillActive: '#e0d3c8',
        connectPillText: '#7d675b',
        connectPillActiveText: '#4a3024',
        terminalPill: 'rgba(255,255,255,0.06)',
        terminalPillActive: '#4b2c1f',
        terminalPillText: '#f2ddd0',
        terminalPillActiveText: '#ffd4b0'
      },
      dark: {
        libraryFrameStart: '#2d1b13',
        libraryFrameEnd: '#46291d',
        libraryBorder: 'rgba(255,255,255,0.08)',
        libraryText: '#fff4eb',
        connectFrame: '#22140e',
        connectBorder: '#4a2d20',
        connectText: '#d2b29e',
        terminalFrame: '#1f120d',
        terminalBorder: 'rgba(255,255,255,0.08)',
        terminalText: '#fff0e5',
        canvas: '#22140e',
        canvasSubtle: '#26160f',
        terminalCanvas: '#1d110b',
        panel: '#291810',
        panelStrong: '#22140e',
        panelBorder: 'rgba(255,255,255,0.08)',
        surface: '#312016',
        surfaceStrong: '#3a261a',
        text: '#fff4eb',
        muted: '#d0ae99',
        accent: '#ffb27d',
        accentSoft: '#4b2c1f',
        accentContrast: '#341a0e',
        success: '#b7d98e',
        successSoft: '#252113',
        warning: '#ffd17c',
        warningSoft: '#332312',
        danger: '#ffac9f',
        dangerSoft: '#351815',
        badge: '#ffb27d',
        libraryPill: 'rgba(255,255,255,0.08)',
        libraryPillActive: 'rgba(255,255,255,0.14)',
        libraryPillText: '#efd8ca',
        libraryPillActiveText: '#ffffff',
        connectPill: '#342116',
        connectPillActive: '#4a2d20',
        connectPillText: '#e2beaa',
        connectPillActiveText: '#fff4eb',
        terminalPill: 'rgba(255,255,255,0.06)',
        terminalPillActive: '#533122',
        terminalPillText: '#f2ddcf',
        terminalPillActiveText: '#ffd9b7'
      }
    }
  }
}

export const APP_THEME_PRESETS = [PRESET_DEFINITIONS[DEFAULT_APP_THEME_PRESET]]
const ALL_THEME_CSS_VAR_KEYS = Array.from(
  new Set(
    APP_THEME_PRESETS.flatMap((preset) =>
      Object.values(preset.cssVars).flatMap((vars) => Object.keys(vars))
    )
  )
)

export function isAppThemePreset(value: unknown): value is AppThemePreset {
  return value === DEFAULT_APP_THEME_PRESET
}

export function resolveAppThemeMode(value?: string | null): AppThemeMode {
  return value === 'light' ? 'light' : 'dark'
}

export function getThemePresetDefinition(preset: AppThemePreset): ThemePresetDefinition {
  return preset === DEFAULT_APP_THEME_PRESET
    ? PRESET_DEFINITIONS[preset]
    : PRESET_DEFINITIONS[DEFAULT_APP_THEME_PRESET]
}

export function getTerminalTheme(preset: AppThemePreset, mode: AppThemeMode): ITheme {
  return getThemePresetDefinition(preset).terminal[mode]
}

export function getSshChromePalette(preset: AppThemePreset, mode: AppThemeMode): SshChromePalette {
  return getThemePresetDefinition(preset).ssh[mode]
}

export function applyThemePresetCssVars(
  root: HTMLElement,
  preset: AppThemePreset,
  mode: AppThemeMode
): void {
  const cssVars = getThemePresetDefinition(preset).cssVars[mode]
  for (const key of ALL_THEME_CSS_VAR_KEYS) {
    root.style.removeProperty(key)
  }
  for (const [key, value] of Object.entries(cssVars)) {
    root.style.setProperty(key, value)
  }
}
